// Placeholder for v0-generated Maya Chen portfolio.
// Paste the v0 component output here, replacing this entire file.
// Then add `import Link from "next/link"; <Link href="/demo/maya">See a demo</Link>`
// somewhere on the landing hero.

import Link from "next/link";
import { ScoutMark } from "@/components/scout-mark";

export const metadata = {
  title: "Maya Chen · ScoutFolio demo",
  description: "Example portfolio generated by the ScoutFolio agent.",
};

export default function MayaDemoPage() {
  return (
    <main className="min-h-dvh px-6 py-24">
      <div className="mx-auto max-w-2xl text-center">
        <Link
          href="/"
          className="inline-flex items-center gap-2 text-foreground"
        >
          <ScoutMark className="size-4 text-accent" />
          <span className="font-serif text-xl">ScoutFolio</span>
        </Link>
        <p className="eyebrow mt-12">Demo · placeholder</p>
        <h1 className="mt-3 font-serif text-4xl tracking-[-0.02em] text-foreground sm:text-5xl">
          Paste your v0-generated{" "}
          <span className="italic">Maya Chen</span> portfolio here.
        </h1>
        <p className="mt-6 text-muted">
          Replace this entire file (
          <code className="rounded bg-foreground/[0.06] px-1.5 py-0.5 font-mono text-xs">
            app/demo/maya/page.tsx
          </code>
          ) with the v0 output. Use{" "}
          <code className="rounded bg-foreground/[0.06] px-1.5 py-0.5 font-mono text-xs">
            export default function MayaDemoPage()
          </code>{" "}
          as the export.
        </p>
      </div>
    </main>
  );
}
